# appveyor file

# build version format
version: "{build}"

platform: x64

image: Visual Studio 2015

# Set a known clone folder
clone_folder: c:\projects\node-printer

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "Matteo Tafani Alunno"
  - git config --global user.email mtafanialunno@vendini.com

# what combinations to test
environment:
  matrix:
    # Node.js
    - nodejs_version: "6.5"
      build_electron: "true"
    - nodejs_version: "6.9"
      build_electron: "true"

matrix:
  fast_finish: true
  allow_failures:
    - nodejs_version: "6.9"

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version x64
  - cmd: SET PATH=c:\python27;%PATH%
  - cmd: SET JOBS=4
  - cmd: SET BUILD_ONLY=true
  - npm install -g node-gyp node-pre-gyp
  - npm install --build-from-source --msvs_version=2013

test_script:
  - node --version
  - npm --version
  - npm test

after_test:
  - node-gyp clean
  - ps: ./tools/buildWindows.ps1

build: off

artifacts:
  - path: 'build\stage\**\*.tar.gz'

branches:
  only:
    - master
